apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Tag
  formSchema:
    - $formkit: "text"
      name: "desc"
      label: "简介"