apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-corner-setting
spec:
  forms:
    #基础模块
    - group: oIndex
      label: 基础模块
      formSchema:
        #LOGO展示
        - $formkit: group
          label: LOGO展示
          name: sideWeb
          help: 自定义LOGO显示规则
          children:
            - $formkit: select
              name: site_enabled
              id: site_enabled
              key: site_enabled
              value: "default"
              options:
                - label: 默认
                  value: "default"
                - label: 自定义
                  value: "custom"
            - $formkit: attachment
              if: "$get(site_enabled).value === 'custom'"
              accepts:
                - "image/*"
              name: custom_logo
              id: custom_logo
              key: custom_logo
              label: Logo
              value: ""
        #Hero展示
        - $formkit: group
          label: Hero模块
          name: Hero
          help: 自定义Hero显示规则
          children:
            #Hero开关
            - $formkit: switch
              name: Hero_enabled
              id: Hero_enabled
              key: Hero_enabled
              label: 启用Hero模块
              value: false
            - $formkit: select
              name: style
              id: style
              key: style
              label: 类型
              if: $get(Hero_enabled).value
              placeholder: 请选择类型
              value: ""
              options:
                - label: 选择文章
                  value: selectPost
                - label: 自定义轮播
                  value: customPost
            #文章选择
            - $formkit: postSelect
              name: heroPost
              id: heroPost
              key: heroPost
              label: 文章
              validation: required
              if: $get(style).value === 'selectPost'
              value: ""
            #自定义
            - $formkit: array
              name: customHero
              id: customHero
              key: customHero
              label: 大屏展示图
              if: $get(style).value === 'customPost'
              value: []
              itemLabels:
                - type: image
                  label: $value.customImg
                - type: text
                  label: $value.customTag
                - type: text
                  label: $value.customTitle
              children:
                - $formkit: attachment
                  accepts:
                    - "image/*"
                  name: customImg
                  id: customImg
                  key: customImg
                  label: 图片
                  help: 请选择图片
                  value: ""
                  if: $get(style).value === 'customPost'
                - $formkit: text
                  name: customTag
                  id: customTag
                  key: customTag
                  label: 标签
                  help: 请填写标签
                  if: $get(style).value === 'customPost'
                - $formkit: text
                  name: customTitle
                  id: customTitle
                  key: customTitle
                  label: 标题
                  help: 请填写标题
                  value: ""
                  if: $get(style).value === 'customPost'
                - $formkit: text
                  name: customDesc
                  id: customDesc
                  key: customDesc
                  label: 描述
                  help: 请填写描述
                  value: ""
                  if: $get(style).value === 'customPost'
                - $formkit: text
                  name: customBtn
                  id: customBtn
                  key: customBtn
                  label: 按钮
                  help: 请填写按钮名称
                  value: ""
                  if: $get(style).value === 'customPost'
                - $formkit: text
                  name: customLink
                  id: customLink
                  key: customLink
                  label: 链接
                  help: 请填写链接
                  value: ""
                  if: $get(style).value === 'customPost'
        #最新文章
        - $formkit: group
          label: 文章显示
          name: Blog
          children:
            - $formkit: switch
              name: blog_enabled
              id: blog_enabled
              key: blog_enabled
              label: 启用主题预设
            - $formkit: text
              name: blogTitle
              id: blogTitle
              key: blogTitle
              label: 标题
              value: ""
              if: $get(blog_enabled).value
            - $formkit: text
              name: blogDesc
              id: blogDesc
              key: blogDesc
              label: 描述
              value: ""
              if: $get(blog_enabled).value
            - $formkit: select
              name: blogStyle
              id: blogStyle
              key: blogStyle
              label: 显示条数
              value: 5
              if: $get(blog_enabled).value
              options:
                - label: 5
                  value: 5
                - label: 8
                  value: 8
            - $formkit: group
              label: 查看更多
              name: more
              if: $get(blog_enabled).value
              children:
                - $formkit: text
                  name: moreTitle
                  id: moreTitle
                  key: moreTitle
                  label: 标题
                  value: "探索更多精彩内容，发现更多故事"
                - $formkit: text
                  name: moreLink
                  id: moreLink
                  key: moreLink
                  label: 提示
                  value: "查看更多"
    #分类模块
    - group: oCat
      label: 分类模块
      formSchema:
        - $formkit: switch
          name: oCat_enabled
          id: oCat_enabled
          key: oCat_enabled
          label: 启用分类展示
        - $formkit: select
          name: oCat_style
          id: oCat_style
          key: oCat_style
          label: 分类展示样式
          value: default
          if: $get(oCat_enabled).value
          options:
            - label: 常规
              value: default
            - label: 列表
              value: list
        - $formkit: group
          label: 分类展示
          name: Category
          if: $get(oCat_enabled).value
          children:
            - $formkit: text
              name: categoryTitle
              id: categoryTitle
              key: categoryTitle
              label: 标题
              value: ""
            - $formkit: text
              name: categoryDesc
              id: categoryDesc
              key: categoryDesc
              label: 描述
              value: ""
            - $formkit: repeater
              if: $get(oCat_style).value == "default"
              name: categoryList
              id: categoryList
              key: categoryList
              label: 分类选择
              value: []
              children:
                - $formkit: text
                  name: categoryItem_title
                  id: categoryItem_title
                  key: categoryItem_title
                  label: 分类标题
                  value: ""
                  validation: required
                - $formkit: text
                  name: categoryItem_desc
                  id: categoryItem_desc
                  key: categoryItem_desc
                  label: 描述
                  value: ""
                  validation: required
                - $formkit: categorySelect
                  name: categoryItem_list
                  id: categoryItem_list
                  key: categoryItem_list
                  label: 子分类
                  multiple: true
                  value: []
            - $formkit: categorySelect
              if: $get(oCat_style).value == "list"
              name: categoryItem_list
              id: categoryItem_list
              key: categoryItem_list
              label: 分类选择
              value: []
              multiple: true
              validation: required
    #链接模块
    - group: oFriends
      label: 链接模块
      formSchema:
        - $formkit: switch
          name: friends_enabled
          id: friends_enabled
          key: friends_enabled
          label: 启用链接展示
        - $formkit: group
          label: 链接展示
          name: Friends
          id: Friends
          key: Friends
          if: $get(friends_enabled).value
          children:
            - $formkit: text
              name: friendsTitle
              id: friendsTitle
              key: friendsTitle
              label: 标题
              value: ""
            - $formkit: text
              name: friendsDesc
              id: friendsDesc
              key: friendsDesc
              label: 描述
              value: ""
            - $formkit: select
              name: friendsStyle
              id: friendsStyle
              key: friendsStyle
              label: 样式
              value: links
              options:
                - label: 链接/Links
                  value: links
                - label: 自定义
                  value: custom
            - $formkit: select
              name: linkName
              id: linkName
              key: linkName
              label: 选择分组
              if: "$get(friendsStyle).value === 'links'"
              help: 此选项需要链接插件支持
              clearable: true
              action: /apis/core.halo.run/v1alpha1/linkgroups
              validation: required
              requestOption:
                method: GET
                pageField: page
                sizeField: size
                totalField: total
                itemsField: items
                labelField: spec.displayName
                valueField: metadata.name
                validation: required
        - $formkit: group
          label: 自定义列表
          name: Custom
          if: "$get(friendsStyle).value === 'custom'"
          children:
            - $formkit: array
              name: customLinks
              id: customLinks
              key: customLinks
              value: []
              itemLabels:
                - type: image
                  label: $value.customLink_icon
                - type: text
                  label: $value.customLink_title
                - type: text
                  label: $value.customLink_url
                - type: text
                  label: $value.customLink_tag
              children:
                - $formkit: attachment
                  name: customLink_icon
                  id: customLink_icon
                  key: customLink_icon
                  label: 图标
                  accepts:
                    - "image/png"
                  value: ""
                - $formkit: text
                  name: customLink_tag
                  id: customLink_tag
                  key: customLink_tag
                  label: 标签
                  validation: required
                - $formkit: text
                  name: customLink_title
                  id: customLink_title
                  key: customLink_title
                  label: 标题
                  value: ""
                  validation: required
                - $formkit: text
                  name: customLink_desc
                  id: customLink_desc
                  key: customLink_desc
                  label: 描述
                - $formkit: text
                  name: customLink_url
                  id: customLink_url
                  key: customLink_url
                  label: 链接
                  value: ""
                  validation: required
                - $formkit: text
                  name: customLink_time
                  id: customLink_time
                  key: customLink_time
                  label: 时间
                  value: ""
                  validation: required
    #关于模块
    - group: oInfo
      label: 关于模块
      formSchema:
        - $formkit: switch
          name: info_enabled
          id: info_enabled
          key: info_enabled
          label: 启用关于展示
        - $formkit: group
          label: 关于展示
          name: Info
          if: $get(info_enabled).value
          children:
            - $formkit: text
              name: infoTitle
              id: infoTitle
              key: infoTitle
              label: 标题
              value: ""
            - $formkit: text
              name: infoDesc
              id: infoDesc
              key: infoDesc
              label: 描述
              value: ""
        - $formkit: group
          label: 个人信息
          name: infoUser
          id: infoUser
          key: infoUser
          if: $get(info_enabled).value
          children:
            - $formkit: attachment
              accepts:
                - "image/*"
              name: infoUser_logo
              label: 头像
              value: ""
              validation: required
            - $formkit: text
              name: infoUser_name
              id: infoUser_name
              key: infoUser_name
              label: 昵称
              value: ""
              validation: required
            - $formkit: text
              name: infoUser_tag
              id: infoUser_tag
              key: infoUser_tag
              label: 标签
              value: ""
              validation: required
            - $formkit: code
              name: infoUser_desc
              id: infoUser_desc
              key: infoUser_desc
              label: 描述
              height: 100px
              language: html
              validation: required
        - $formkit: select
          if: $get(info_enabled).value
          name: infoSocial_type
          id: infoSocial_type
          key: infoSocial_type
          label: 社交配置
          placeholder: 请选择
          options:
            - value: default
              label: 置入个人信息
            - value: infoOther
              label: 置入其他信息
        - $formkit: group
          if: "$get(infoSocial_type).value === 'infoOther' || $get(infoSocial_type).value === 'default'"
          label: 社交信息
          name: infoSocial
          id: infoSocial
          key: infoSocial
          children:
            - $formkit: text
              name: infoSocial_title
              id: infoSocial_title
              key: infoSocial_title
              label: 标题
              value: ""
              validation: required
            - $formkit: array
              name: socialList
              id: socialList
              key: socialList
              label: 社交信息
              value: []
              itemLabels:
                - type: iconify
                  label: $value.socialItem_icon
                - type: text
                  label: $value.socialItem_title
                - type: text
                  label: $value.socialItem_url
              children:
                - $formkit: iconify
                  name: socialItem_icon
                  id: socialItem_icon
                  key: socialItem_icon
                  label: 图标
                  format: svg
                  help: 建议大小设置为"100%"
                - $formkit: text
                  name: socialItem_title
                  id: socialItem_title
                  key: socialItem_title
                  label: 标题
                  value: ""
                  validation: required
                - $formkit: text
                  name: socialItem_url
                  id: socialItem_url
                  key: socialItem_url
                  label: 链接
                  value: ""
                  validation: required
        - $formkit: group
          label: 其它信息
          if: $get(infoSocial_type).value == 'infoOther'
          name: infoOther
          children:
            - $formkit: text
              name: infoOther_title
              id: infoOther_title
              key: infoOther_title
              label: 标题
              value: ""
              validation: required
            - $formkit: code
              name: infoOther_desc
              id: infoOther_desc
              key: infoOther_desc
              label: 描述
              height: 100px
              language: html
              validation: required

        - $formkit: group
          label: 近期动向
          name: infoTrend
          id: infoTrend
          key: infoTrend
          if: $get(infoSocial_type).value == 'infoOther'
          children:
            - $formkit: text
              name: infoTrend_title
              id: infoTrend_title
              key: infoTrend_title
              label: 标题
              value: ""
              validation: required
            - $formkit: code
              name: infoTrend_desc
              id: infoTrend_desc
              key: infoTrend_desc
              label: 描述
              height: 100px
              language: html
              validation: required
    #页脚模块
    - group: oFooter
      label: 页脚模块
      formSchema:
        - $formkit: switch
          name: beian_enabled
          id: beian_enabled
          key: beian_enabled
          label: 开启备案信息
          value: false
        - $formkit: group
          name: beian_items
          id: beian_items
          key: beian_items
          if: $get(beian_enabled).value
          label: 备案信息设置
          children:
            - $formkit: text
              name: icp
              id: icp
              key: icp
              label: ICP备案
            - $formkit: text
              name: gongan
              id: gongan
              key: gongan
              label: 公安备案
    #一般设置
    - group: oGeneral
      label: 一般设置
      formSchema:
        - $formkit: group
          name: read
          help: 此选项开启后可修改模版页面信息，如：归档、链接页。
          children:
            - $formkit: checkbox
              name: oGeneralAgree
              id: oGeneralAgree
              key: oGeneralAgree
              label: 我已知晓注意事项
        - $formkit: group
          label: 归档 / archives
          name: archivesSetting
          if: $get(oGeneralAgree).value
          children:
            - $formkit: switch
              name: oGeneraArchives
              id: oGeneraArchives
              key: oGeneraArchives
              label: 启用
              value: false
            - $formkit: text
              name: archivesTitle
              id: archivesTitle
              key: archivesTitle
              label: 标题
              value: ""
              if: $get(oGeneraArchives).value
            - $formkit: text
              name: archivesDesc
              id: archivesDesc
              key: archivesDesc
              label: 描述
              value: ""
              if: $get(oGeneraArchives).value
        - $formkit: group
          label: 链接 / links
          name: linksSetting
          if: $get(oGeneralAgree).value
          children:
            - $formkit: switch
              name: oGeneraLinks
              id: oGeneraLinks
              key: oGeneraLinks
              label: 显示评论
              value: false
